stages:
  prepare:
    cmd: python src/prepare_data.py
    deps:
    - src/prepare_data.py
    - data/raw/IMDB_Dataset.csv
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  train:
    cmd: python src/train.py
    deps:
    - data/processed/train.csv
    - src/train.py
    outs:
    - artifacts/metrics.json
    - artifacts/model.pkl
    - artifacts/vectorizer.pkl
