name: MLOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mlops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[all] dagshub mlflow

      - name: Configure DVC Remote for Dagshub
        run: |
          dvc remote add -d dagshub https://dagshub.com/Dharsh/imdb-response-demo.dvc
          dvc remote modify dagshub --local auth basic
          dvc remote modify dagshub --local user Dharsh
          dvc remote modify dagshub --local password 4f3284cea30d20043975370eef81965d94e13fe1

      - name: Pull data from Dagshub
        run: dvc pull -r dagshub --force

      - name: Run DVC pipeline
        run: dvc repro

      - name: Push data to Dagshub
        run: dvc push -r dagshub

      - name: Commit and push changes (if any)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Update artifacts and metrics [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
