name: IMDB Sentiment CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
      # ------------------------
      # Checkout repo
      # ------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # ------------------------
      # Setup Python
      # ------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # ------------------------
      # Install dependencies
      # ------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[s3]  # include your remote type if using s3/dagshub
          
      # ------------------------
      # Configure DVC remote (Dagshub)
      # ------------------------
      - name: Configure DVC remote
        run: |
          dvc remote modify dagshub --local auth basic
          dvc remote modify dagshub --local user Dharsh
          dvc remote modify dagshub --local password 4f3284cea30d20043975370eef81965d94e13fe1

      # ------------------------
      # Pull all DVC outputs
      # ------------------------
      - name: Pull DVC outputs
        run: dvc pull -r dagshub --force

      # ------------------------
      # Reproduce pipeline if needed
      # ------------------------
      - name: Reproduce DVC pipeline
        run: dvc repro

      # ------------------------
      # Verify files are present
      # ------------------------
      - name: Verify pulled files
        run: |
          echo "Data processed:"
          ls -l data/processed/
          echo "Artifacts:"
          ls -l artifacts/

      # ------------------------
      # Run a simple test on API
      # ------------------------
      - name: Test API import
        run: |
          python -c "from src import app; print('App imported successfully')"

