name: IMDB Sentiment CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc[s3] scikit-learn pandas joblib mlflow fastapi uvicorn

      - name: Configure DVC remote for Dagshub
        run: |
          dvc remote modify dagshub --local auth basic
          dvc remote modify dagshub --local user Dharsh
          dvc remote modify dagshub --local password 4f3284cea30d20043975370eef81965d94e13fe1

      - name: Pull all DVC tracked files from Dagshub
        run: dvc pull -r dagshub --force

      - name: Verify pulled files
        run: |
          echo "Data files:"
          ls -l data/processed/
          echo "Model files:"
          ls -l artifacts/
          echo "Metrics:"
          ls -l metrics/

      - name: Reproduce DVC pipeline
        run: dvc repro

      - name: push updated outputs to Dagshub
        run: dvc push -r dagshub
